<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="G1-HCS2MQ3-L" failures="4" tests="8" name="ChromeTest" time="58.893" errors="0" timestamp="2023-03-03T11:12:48 IST">
  <testcase classname="StarAppTesting.LoginTests" name="TC1_1" time="11.203"/>
  <testcase classname="StarAppTesting.LoginTests" name="TC1_2" time="10.983">
    <failure type="java.lang.AssertionError" message="expected [Hi] but found [Hi Rudraksh]">
      <![CDATA[java.lang.AssertionError: expected [Hi] but found [Hi Rudraksh]
at StarAppTesting.LoginTests.TC1_2(LoginTests.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC1_2 -->
  <testcase classname="StarAppTesting.LoginTests" name="TC1_2" time="10.731"/>
  <testcase classname="StarAppTesting.LoginTests" name="TC1_3" time="1.708"/>
  <testcase classname="StarAppTesting.LoginTests" name="TC1_3" time="1.628"/>
  <testcase classname="StarAppTesting.LoginTests" name="TC1_4" time="1.605">
    <failure type="java.lang.AssertionError" message="expected [Invalid Credentials] but found [Invalid Credentitals]">
      <![CDATA[java.lang.AssertionError: expected [Invalid Credentials] but found [Invalid Credentitals]
at StarAppTesting.LoginTests.TC1_4(LoginTests.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC1_4 -->
  <testcase classname="StarAppTesting.LoginTests" name="TC1_4" time="1.589">
    <failure type="java.lang.AssertionError" message="expected [Invalid Credentials] but found [Invalid Credentitals]">
      <![CDATA[java.lang.AssertionError: expected [Invalid Credentials] but found [Invalid Credentitals]
at StarAppTesting.LoginTests.TC1_4(LoginTests.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC1_4 -->
  <testcase classname="StarAppTesting.LoginTests" name="TC1_4" time="1.574">
    <failure type="java.lang.AssertionError" message="expected [Invalid Credentials] but found [Invalid Credentitals]">
      <![CDATA[java.lang.AssertionError: expected [Invalid Credentials] but found [Invalid Credentitals]
at StarAppTesting.LoginTests.TC1_4(LoginTests.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC1_4 -->
</testsuite> <!-- ChromeTest -->
